### ISSUE TITLE
application crashes 

### ISSUE THREAD

**Issue by SuperLargeEggplant** [aiczk/Astro#12]
At first the application crashes with ID.
I can't verify this withparty play and don't have much useful information.

I tried it with the house scarecrow (sorry, I don't know the exact English name) and it doesn't crash when solo, but if I just do a malefic with PLD in the party, it crashes the application.

If I try to execute the malefic in combat with auto attack, etc., it crashes before the casting is finished.
It seems that the presence or absence of card pre-drawing has no effect on whether or not the application crashes.

I have all options on Astro turned on.

**Comment by abranon** [comment]
I can confirm I crashed with a prepull malefic with auto attack on, however unsure if tanks makes a difference as I had a GNB/DRK and WAR/DRK comboes both times.
There was no new error received but did receive this;

2022-06-25 19:10:45.122 -05:00 [ERR] Exception on ProcessZonePacketDown hook. Header: 80-82-49-90-FC-7F-00-00-20-81-22-AB-58-02-00-00-14-00-4C-01-00-00-1F-01-04-A4-B7-62-00-00-00-00
System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'arcanum')
Actual value was None.
   at Astro.Helper.AstrologianHelper.GetCardType(AstrologianCard arcanum) in D:\Develop\Astro\Astro\Helper\AstrologianHelper.cs:line 134
   at Astro.Helper.AstrologianHelper.GetOptimumTargetId() in D:\Develop\Astro\Astro\Helper\AstrologianHelper.cs:line 82
   at Astro.Astro.<>c.<.ctor>b__6_13(Unit _) in D:\Develop\Astro\Astro\Astro.cs:line 70
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Astro.Astro.ReceiveAbilityDetour(UInt32 sourceId, IntPtr sourceCharacter, IntPtr position, IntPtr effectHeader, IntPtr effectArray, IntPtr effectTrail) in D:\Develop\Astro\Astro\Astro.cs:line 99
   at DelvUI.Interface.PartyCooldowns.PartyCooldownsManager.OnActionUsed(Int32 characterId, IntPtr characterAddress, IntPtr position, IntPtr effect, IntPtr unk1, IntPtr unk2) in D:\Projects\delvui\DelvUI\Interface\PartyCooldowns\PartyCooldownsManager.cs:line 194
   at JobBars.JobBars.ReceiveActionEffect(Int32 sourceId, IntPtr sourceCharacter, IntPtr pos, IntPtr effectHeader, IntPtr effectArray, IntPtr effectTrail)
   at NoClippy.Game.ReceiveActionEffectDetour(Int32 sourceActorID, IntPtr sourceActor, IntPtr vectorPosition, IntPtr effectHeader, IntPtr effectArray, IntPtr effectTrail) in D:\a\NoClippy\NoClippy\Game.cs:line 79
   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 134
2022-06-25 19:10:45.122 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0yNVQxOToxMDo0NS4xMjI3Ny0wNTowMCIsIkluZm8iOiJTeXN0ZW0uQXJndW1lbnRPdXRPZlJhbmdlRXhjZXB0aW9uOiBFeGNlcHRpb24gb2YgdHlwZSAnU3lzdGVtLkFyZ3VtZW50T3V0T2ZSYW5nZUV4Y2VwdGlvbicgd2FzIHRocm93bi4gKFBhcmFtZXRlciAnYXJjYW51bScpXHJcbkFjdHVhbCB2YWx1ZSB3YXMgTm9uZS5cclxuICAgYXQgQXN0cm8uSGVscGVyLkFzdHJvbG9naWFuSGVscGVyLkdldENhcmRUeXBlKEFzdHJvbG9naWFuQ2FyZCBhcmNhbnVtKSBpbiBEOlxcRGV2ZWxvcFxcQXN0cm9cXEFzdHJvXFxIZWxwZXJcXEFzdHJvbG9naWFuSGVscGVyLmNzOmxpbmUgMTM0XHJcbiAgIGF0IEFzdHJvLkhlbHBlci5Bc3Ryb2xvZ2lhbkhlbHBlci5HZXRPcHRpbXVtVGFyZ2V0SWQoKSBpbiBEOlxcRGV2ZWxvcFxcQXN0cm9cXEFzdHJvXFxIZWxwZXJcXEFzdHJvbG9naWFuSGVscGVyLmNzOmxpbmUgODJcclxuICAgYXQgQXN0cm8uQXN0cm8uPD5jLjwuY3Rvcj5iX182XzEzKFVuaXQgXykgaW4gRDpcXERldmVsb3BcXEFzdHJvXFxBc3Ryb1xcQXN0cm8uY3M6bGluZSA3MFxyXG4gICBhdCBTeXN0ZW0uUmVhY3RpdmUuQW5vbnltb3VzU2FmZU9ic2VydmVyYDEuT25OZXh0KFQgdmFsdWUpXHJcbiAgIGF0IFN5c3RlbS5SZWFjdGl2ZS5TdWJqZWN0cy5TdWJqZWN0YDEuT25OZXh0KFQgdmFsdWUpXHJcbiAgIGF0IEFzdHJvLkFzdHJvLlJlY2VpdmVBYmlsaXR5RGV0b3VyKFVJbnQzMiBzb3VyY2VJZCwgSW50UHRyIHNvdXJjZUNoYXJhY3RlciwgSW50UHRyIHBvc2l0aW9uLCBJbnRQdHIgZWZmZWN0SGVhZGVyLCBJbnRQdHIgZWZmZWN0QXJyYXksIEludFB0ciBlZmZlY3RUcmFpbCkgaW4gRDpcXERldmVsb3BcXEFzdHJvXFxBc3Ryb1xcQXN0cm8uY3M6bGluZSA5OVxyXG4gICBhdCBEZWx2VUkuSW50ZXJmYWNlLlBhcnR5Q29vbGRvd25zLlBhcnR5Q29vbGRvd25zTWFuYWdlci5PbkFjdGlvblVzZWQoSW50MzIgY2hhcmFjdGVySWQsIEludFB0ciBjaGFyYWN0ZXJBZGRyZXNzLCBJbnRQdHIgcG9zaXRpb24sIEludFB0ciBlZmZlY3QsIEludFB0ciB1bmsxLCBJbnRQdHIgdW5rMikgaW4gRDpcXFByb2plY3RzXFxkZWx2dWlcXERlbHZVSVxcSW50ZXJmYWNlXFxQYXJ0eUNvb2xkb3duc1xcUGFydHlDb29sZG93bnNNYW5hZ2VyLmNzOmxpbmUgMTk0XHJcbiAgIGF0IEpvYkJhcnMuSm9iQmFycy5SZWNlaXZlQWN0aW9uRWZmZWN0KEludDMyIHNvdXJjZUlkLCBJbnRQdHIgc291cmNlQ2hhcmFjdGVyLCBJbnRQdHIgcG9zLCBJbnRQdHIgZWZmZWN0SGVhZGVyLCBJbnRQdHIgZWZmZWN0QXJyYXksIEludFB0ciBlZmZlY3RUcmFpbClcclxuICAgYXQgTm9DbGlwcHkuR2FtZS5SZWNlaXZlQWN0aW9uRWZmZWN0RGV0b3VyKEludDMyIHNvdXJjZUFjdG9ySUQsIEludFB0ciBzb3VyY2VBY3RvciwgSW50UHRyIHZlY3RvclBvc2l0aW9uLCBJbnRQdHIgZWZmZWN0SGVhZGVyLCBJbnRQdHIgZWZmZWN0QXJyYXksIEludFB0ciBlZmZlY3RUcmFpbCkgaW4gRDpcXGFcXE5vQ2xpcHB5XFxOb0NsaXBweVxcR2FtZS5jczpsaW5lIDc5XHJcbiAgIGF0IFhJVlNsb3RoQ29tYm8uRGF0YS5BY3Rpb25XYXRjaGluZy5SZWNlaXZlQWN0aW9uRWZmZWN0RGV0b3VyKEludDMyIHNvdXJjZU9iamVjdElkLCBJbnRQdHIgc291cmNlQWN0b3IsIEludFB0ciBwb3NpdGlvbiwgSW50UHRyIGVmZmVjdEhlYWRlciwgSW50UHRyIGVmZmVjdEFycmF5LCBJbnRQdHIgZWZmZWN0VHJhaWwpIGluIEQ6XFxhXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxYSVZTbG90aENvbWJvXFxEYXRhXFxBY3Rpb25XYXRjaGluZy5jczpsaW5lIDI2XHJcbiAgIGF0IERhbGFtdWQuR2FtZS5OZXR3b3JrLkdhbWVOZXR3b3JrLlByb2Nlc3Nab25lUGFja2V0RG93bkRldG91cihJbnRQdHIgYSwgVUludDMyIHRhcmdldElkLCBJbnRQdHIgZGF0YVB0cikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcTmV0d29ya1xcR2FtZU5ldHdvcmsuY3M6bGluZSAxMzQiLCJDb250ZXh0IjoiRXhjZXB0aW9uIG9uIFByb2Nlc3Nab25lUGFja2V0RG93biBob29rLiBIZWFkZXI6IDgwLTgyLTQ5LTkwLUZDLTdGLTAwLTAwLTIwLTgxLTIyLUFCLTU4LTAyLTAwLTAwLTE0LTAwLTRDLTAxLTAwLTAwLTFGLTAxLTA0LUE0LUI3LTYyLTAwLTAwLTAwLTAwIn0=


------------------------------------

and this was what was notated at crash from injector though not sure if it helps any:

2022-06-22 16:15:56.602 -05:00 [ERR] [GameStart] Uncaught error during initialization, trying to kill process
Dalamud.Injector.GameStart+GameStartException: Game exited prematurely.
   at Dalamud.Injector.GameStart.LaunchGame(String workingDir, String exePath, String arguments, Boolean dontFixAcl, Action`1 beforeResume, Boolean waitForGameWindow) in C:\goatsoft\companysecrets\injector\GameStart.cs:line 138
2022-06-22 16:15:56.619 -05:00 [ERR] A fatal error has occurred.
Dalamud.Injector.GameStart+GameStartException: Game exited prematurely.
   at Dalamud.Injector.GameStart.LaunchGame(String workingDir, String exePath, String arguments, Boolean dontFixAcl, Action`1 beforeResume, Boolean waitForGameWindow) in C:\goatsoft\companysecrets\injector\GameStart.cs:line 138
   at Dalamud.Injector.EntryPoint.ProcessLaunchCommand(List`1 args, DalamudStartInfo dalamudStartInfo) in C:\goatsoft\companysecrets\injector\EntryPoint.cs:line 597
   at Dalamud.Injector.EntryPoint.Main(Int32 argc, IntPtr argvPtr) in C:\goatsoft\companysecrets\injector\EntryPoint.cs:line 95

**Comment by aiczk** [comment]
Fixed a possible cause of crash in ver1.20.
I apologize for this.

Thanks for giving me the log.

**Comment by SuperLargeEggplant** [comment]
I do a lot of things and no longer get application crashes.
Thank you :)
